name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint project
        run: yarn lint

      - name: Run unit tests
        run: yarn test:ci

      - name: Test Report
        # run this step even if previous step failed
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests # Name of the check run which will be created
          path: reports/unit-tests/*.xml # Path to test results
          reporter: jest-junit # Format of test results

      - name: Build
        run: yarn build
        if: success()
